version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/carlpett/bzfttr53rdutil
    steps:
      - checkout
      - run: go get github.com/mitchellh/gox
      - run: make test
      - run: make crossbuild
      - store_artifacts:
          path: binaries
          destination: binaries
      - persist_to_workspace:
          root: binaries
          paths:
            - "*"
  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/carlpett/bzfttr53rdutil
    steps:
      - checkout
      - attach_workspace:
          at: binaries
      - run: make release

workflows:
  version: 2
  github:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - build